### PR TITLE
CSD-19 opportunities

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Added opportunity content type
- Added field on spotlights to relate the two content types
- styles to be done later

# Need Review By (Date)
- 4/8

# Urgency
- medium

# Steps to Test (either locally or via tugboat)
1. `composer require su-hkku/cardinal_service_profile:dev-CSD-19-opportunities`
1. `blt drupal:sync --site=cardinalservice`
1. Verify you can create an opportunity.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
OK @jbickar can you give it another try. with the latest `1.x` branch of `ace-gryphon`. I've also updated the test steps.

**Comment by jbickar** [comment]
I'm trying to get to this today.

**Comment by jbickar** [comment]
I get an error with pcov. Looks like that needs to be in the lando container as well as on the host OS?

```
lando blt drupal:sync --site=cardinalservice
> source:build:composer
Gathering patches for root package.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - pcov/clobber v2.0.3 requires ext-pcov ^1.0 -> the requested PHP extension pcov is missing from your system.
    - pcov/clobber v2.0.3 requires ext-pcov ^1.0 -> the requested PHP extension pcov is missing from your system.
    - Installation request for pcov/clobber v2.0.3 -> satisfiable by pcov/clobber[v2.0.3].

```

I'll keep banging on it but that's where I'm at.

**Comment by jbickar** [comment]
Looks like tweaking the `.lando.yml` file like this worked:

```
services:
  appserver:
    build_as_root:
      - apt-get update -y && apt-get install
      - pecl install pcov
      - docker-php-ext-enable pcov
    ssl: true
    config:
      php: lando/php.ini
```

**Comment by jbickar** [comment]
[I wonder where I found that snippet...](https://hub.docker.com/layers/pookmish/drupal8ci/pcov/images/sha256-062f825bee8534022e3e0e6922898d8b985ba37ecfbe4086f85c705d82c5697d?context=explore)

**Comment by pookmish** [comment]
oh i HATE how BLT does composer things. :rage:

**Comment by jbickar** [comment]
- Date field granularity can use some UX work (e.g., if you don't enter a time, it should default to 00:00:00)
- "Type", "Time of Year", and "Open To?" don't have any values (I'm presuming these are taxonomy fields)

I'm guessing these don't matter too much if these are all being imported from SOLO and not manually entered.

**Comment by pookmish** [comment]
Yeah 90% of the form will be autopopulated by importers.

**Pull request merged**
