### PR TITLE
CSD-272 Added aria-labelledby to AutoComplete component

### PR DESCRIPTION
**Pull request by rebeccahongsf**
# ALMOST READY FOR REVIEW

# Summary
- Added aria-labelledby to AutoComplete component

# Needed By (Date)
- After confirming that this works on the dev site

# Urgency
- medium

# Steps to Test
1. Pull this branch
2. Clear site cache
3. Inspect Opportunities filter on homepage and list page.
`<div class="MuiAutocomplete-root jss1 su_opp_type-select MuiAutocomplete-hasClearIcon MuiAutocomplete-hasPopupIcon" role="combobox" aria-expanded="false" label="Type of Opportunity" aria-labelledby="su_opp_type-label">`

# Associated Issues and/or People
- [CSD-272](https://stanfordits.atlassian.net/browse/CSD-272)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by rebeccahongsf** [comment]
@pookmish can you please update the dev site when you have a chance? 🙏

**Comment by pookmish** [comment]
@rebeccahongsf I deployed this code to the dev site. Have a look and let me know if this is G2G. I'm happy with the code changes.

**Comment by rebeccahongsf** [comment]
Huzzah! The dev site returns no severity 10 accessibility errors 🎉 

Ready to be reviewed and merged @pookmish 

image

**Comment by pookmish** [comment]
Nice!

**Pull request merged**
