### PR TITLE
CSD-277 Updated spotlight/story styles

### PR DESCRIPTION
**Pull request by rebeccahongsf**
# READY FOR REVIEW

# Summary
- Updated spotlight/story styles for the individual spotlight pages and the spotlight view (located on individual opportunity pages)

# Needed By (Date)
- soon

# Urgency
- medium

# Steps to Test

1. Checkout this branch locally
2. Clear cache
3. Review the following and compare to this [Figma Mock](https://www.figma.com/file/CpblbZldiGM6oYawa9aB4Q/Look-%26-Feel?node-id=1%3A2128)
- Individual spotlight page 
- Spotlight display on individual opportunity page
- Stories list page

# Associated Issues and/or People
- [CSD-277](https://stanfordits.atlassian.net/browse/CSD-277)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by rebeccahongsf** [comment]
The conditional statement for the `{{ link }}` within the [twig template](https://github.com/SU-HKKU/cardinal_service_profile/blob/8.x-1.x/themes/cardinal_service/templates/patterns/pattern-quote.html.twig#L7) isn't working which is why the layout for `no-story` is applied in both views. 🤔 

I was going to try to use kint to see what `{{ link }}` contains to further debug the conditional statement issue but I recall a discussion in dev slack about kint no longer working. 

@pookmish do you have any suggestions on how I might check variables within twig temps? 😄

**Comment by pookmish** [comment]
@rebeccahongsf is this still ready for review now that the changes to the quote template are in place

**Comment by rebeccahongsf** [comment]
Yes! Styles are ready for review @pookmish 😄

**Comment by pookmish** [comment]
Ok but there are alot of styles that wont work anymore after the refactoring of the story view like `story-available`. You'll want to pull the latest from the `8.x-1.x` into this branch and check to see how the styles are applied.

**Comment by rebeccahongsf** [comment]
Now we should be good to go 😅  Thank you Mike!

**Comment by rebeccahongsf** [comment]
approval-han-solo

**Comment by pookmish** [comment]
this just feels uneven 
image

**Pull request merged**
