### PR TITLE
CSD-269 improve csv Importer

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Use migrate module for CSV importer instead of the contrib module that provides little flexibility.

# Need Review By (Date)
- asap

# Urgency
- high

# Steps to Test
1. checkout the stack branch and do `composer install -n`
1. `composer require SU-HKKU/cardinal_service_profile:dev-CSD-269_improve-csv`
1. `blt drupal:sync --site=cardinalservice -n`
1. go to `/admin/content/import` page after logging in
1. download one of the templates from the link at the top of the page
1. populate it with some various rows
1. remove the helper text in the header row. removing the words in the parentheses including the parentheses.
1. upload it and run the import.
1. verify your content was created `/admin/content`

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by joegl** [comment]
I got this setup locally and tried to get a CSV to import a number of times without any success (or errors). I will need to look at it more tomorrow to see if it's an environment issue or not.

**Comment by joegl** [comment]
Are they going to have to remove the parentheses helper text every time? I'm just curious. Maybe the helper text could be in the second row by itself instead of in parentheses in the first row? Then it's really easy to just clear out an entire row at once and get rid of the helper text.

**Comment by joegl** [comment]
I am still getting "Imported 0 items" whenever I try to import an opportunity, but not any great debugging info available except this notice:

```
Notice: Undefined index: skip_on_error in Drupal\migrate_file\Plugin\migrate\process\FileImport->transform() (line 229 of modules/contrib/migrate_file/src/Plugin/migrate/process/FileImport.php).
Drupal\migrate_file\Plugin\migrate\process\FileImport->transform('test', Object, Object, 'image_file') (Line: 394)
Drupal\migrate\MigrateExecutable->processRow(Object) (Line: 203)
Drupal\migrate\MigrateExecutable->import() (Line: 191)
stanford_migrate_execute_migration(Object, 'csv_opportunities') (Line: 185)
Drupal\cardinal_service_profile_helper\Form\CsvImporterForm->submitForm(Array, Object)
call_user_func_array(Array, Array) (Line: 114)
Drupal\Core\Form\FormSubmitter->executeSubmitHandlers(Array, Object) (Line: 52)
Drupal\Core\Form\FormSubmitter->doSubmitForm(Array, Object) (Line: 593)
Drupal\Core\Form\FormBuilder->processForm('csv_importer_form', Array, Object) (Line: 321)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object) (Line: 91)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array) (Line: 123)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 573)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 124)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) (Line: 97)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() (Line: 151)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 68)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 106)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 85)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 52)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 708)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

**Comment by joegl** [comment]
Okay have got this working now. My only concern is that if the values aren't filled with the correct variable types they won't import correctly, and there aren't any validators/errors to point that out. Are they going to be filling in the spreadsheets manually or exporting them from somewhere?

**Comment by pookmish** [comment]
They will be filling them in manually. Every field are regular string fields except for the image url column. I will be building an export of the existing content as well and they can use that to compare

**Comment by joegl** [comment]
> They will be filling them in manually. Every field are regular string fields except for the image url column. I will be building an export of the existing content as well and they can use that to compare

Ok cool. If you're good with that, then everything else looks good to me.

**Pull request merged**
