### PR TITLE
Spotlight node and view improvements

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Added a couple fields to spotlights, migrated field data and used those field in the views and displays.

# Need Review By (Date)
- asap

# Urgency
- medium-high

# Steps to Test
1. checkout this branch
1. `blt drupal:sync --site=cardinalservice`
1. create/view some spotlights
1. verify data still is there for existing spotlights.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by joegl** [comment]
I'd not seen the `{%- -%}` syntax with the "-" in twig before; [neat.](https://twig.symfony.com/doc/3.x/templates.html#whitespace-control)

**Comment by joegl** [comment]
I see the data being migrated successfully between the fields for existing spotlights. However, when I view a spotlight I am not able to see the quote field. Is this intentional?

**Comment by pookmish** [comment]
Yeah, the latest mockups don't display the quote field now.

**Comment by joegl** [comment]
> I see the data being migrated successfully between the fields for existing spotlights. However, when I view a spotlight I am not able to see the quote field. Is this intentional?

This was on the main node display. However, I got the feeling these are meant to display on an opportunity, so I related a spotlight to an opportunity, pulled up the opportunity, and was able to see the quote.

**Pull request merged**
