### PR TITLE
CSD-224 Add fields and view for resources tagging

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Added fields to the basic page to mark it as a resource page.

# Need Review By (Date)
- asap

# Urgency
- medium-high

# Steps to Test
1. `composer require su-hkku/cardinal_service_profile:dev-CSD-224_resources`
1. `blt drupal:sync --site=cardinalservice`
1. verify a basic page has the resource fields at the bottom in a fieldset, but they don't display anywhere.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by joegl** [comment]
I'm having issues with the composer require:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for su-hkku/cardinal_service_profile dev-CSD-224_resources -> satisfiable by su-hkku/cardinal_service_profile[dev-CSD-224_resources].
    - Conclusion: remove drupal/views_taxonomy_term_name_depth 6.0.0-alpha2
    - Conclusion: don't install drupal/views_taxonomy_term_name_depth 6.0.0-alpha2
    - su-hkku/cardinal_service_profile dev-CSD-224_resources requires drupal/views_taxonomy_term_name_depth ^7.0 -> satisfiable by drupal/views_taxonomy_term_name_depth[7.0.0, 7.0.1].
    - Can only install one of: drupal/views_taxonomy_term_name_depth[7.0.0, 6.0.0-alpha2].
    - Can only install one of: drupal/views_taxonomy_term_name_depth[7.0.1, 6.0.0-alpha2].
    - Installation request for drupal/views_taxonomy_term_name_depth (locked at 6.0.0-alpha2) -> satisfiable by drupal/views_taxonomy_term_name_depth[6.0.0-alpha2].
```

**Comment by pookmish** [comment]
what you probably have to do is:
```
composer require su-hkku/cardinal_service_profile:dev-CSD-224_resources --no-update
composer update -n
```

**Comment by joegl** [comment]
> what you probably have to do is:
> 
> ```
> composer require su-hkku/cardinal_service_profile:dev-CSD-224_resources --no-update
> composer update -n
> ```



> what you probably have to do is:
> 
> ```
> composer require su-hkku/cardinal_service_profile:dev-CSD-224_resources --no-update
> composer update -n
> ```

I tried this and am still having issues with composer. It hangs after the $kint.json passage and does this repeatedly:
`Resolving dependencies through SAT
Looking at all rules.
Something's changed, looking at all rules again (pass #38)
`

**Comment by pookmish** [comment]
the `composer update` part takes quite awhile.  i think about 10 - 15 minutes sometimes.

**Comment by joegl** [comment]
> the `composer update` part takes quite awhile. i think about 10 - 15 minutes sometimes.

Alright I'll let it do its thing for a while and see if it resolves itself.

**Comment by joegl** [comment]
> > the `composer update` part takes quite awhile. i think about 10 - 15 minutes sometimes.
> 
> Alright I'll let it do its thing for a while and see if it resolves itself.

It's resolved now. Will start looking at this PR.

**Comment by pookmish** [comment]
yeah the fields and views are normally prefixed with `cs_` but it slipped through. I can prefix the new configs real quick.

**Pull request merged**
